# Generated by Django 2.1.2 on 2018-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('placeid', models.AutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=100, unique=True)),
                ('OpenTime', models.TimeField()),
                ('CloseTime', models.TimeField()),
                ('DaysClosed', models.CharField(max_length=20)),
            ],
        ),
    ]
