# Generated by Django 2.1.2 on 2018-10-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('reminderID', models.AutoField(primary_key=True, serialize=False)),
                ('reminderTitle', models.CharField(max_length=50)),
                ('reminderDetails', models.CharField(max_length=200)),
                ('reminderDate', models.DateField()),
                ('reminderTime', models.TimeField()),
                ('reminderPriority', models.CharField(max_length=6)),
            ],
        ),
    ]
