# Generated by Django 2.1.2 on 2018-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
