# Generated by Django 2.1.2 on 2018-10-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductiveNITK', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='ayush', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
